name: Deploy Structurizr Diagrams

on:
  push:
    paths:
      - "**.dsl"
    branches:
      - main

env:
  STRUCTURIZR_URL: ${{ secrets.STRUCTURIZR_URL }}
  STRUCTURIZR_WORKSPACE_ID: ${{ secrets.STRUCTURIZR_WORKSPACE_ID }}
  STRUCTURIZR_API_KEY: ${{ secrets.STRUCTURIZR_API_KEY }}
  STRUCTURIZR_API_SECRET: ${{ secrets.STRUCTURIZR_API_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed DSL files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.dsl$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Push to Structurizr
        uses: gilbertotcc/structurizr-action@v1
        env:
          STRUCTURIZR_WORKSPACE_ID: ${{ secrets.STRUCTURIZR_WORKSPACE_ID }}
          STRUCTURIZR_API_KEY: ${{ secrets.STRUCTURIZR_API_KEY }}
          STRUCTURIZR_API_SECRET: ${{ secrets.STRUCTURIZR_API_SECRET }}
          STRUCTURIZR_URL: ${{ secrets.STRUCTURIZR_URL }}
        with:
          args: "push -workspace ${{ steps.changed-files.outputs.files }}"
