name: Deploy Structurizr Diagrams

on:
  push:
    paths:
      - "**.dsl"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed DSL files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.dsl$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run structurizr-cli action
        uses: aidmax/structurizr-cli-action@v1
        with:
          id: ${{ secrets.STRUCTURIZR_WORKSPACE_ID }}
          key: ${{ secrets.STRUCTURIZR_API_KEY }}
          secret: ${{ secrets.STRUCTURIZR_API_SECRET }}
          workspace: ${{ steps.changed-files.outputs.files }}
          url: ${{ secrets.STRUCTURIZR_URL }}
