name: Deploy Structurizr Diagrams

on:
  push:
    paths:
      - "**.dsl"
    branches:
      - main
  workflow_dispatch:
    inputs:
      workspace:
        required: true
        description: "Path of workspace to deploy structurizr/<NAME_OF_FILE>.dsl"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/sebastienfi/structurizr-cli-with-bonus:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set workspace from input
        id: input-workspace
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "workspace=${{ github.event.inputs.workspace }}" >> $GITHUB_OUTPUT

      - name: Get changed DSL files
        id: changed-files
        if: github.event_name == 'push'
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.dsl$' || echo "")
          echo "DSL files changed: $CHANGED_FILES"
          echo "workspace=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Extract workspace name
        id: workspace-name
        run: |
          FILE_PATH="${{ steps.changed-files.outputs.workspace || steps.input-workspace.outputs.workspace }}"
          WORKSPACE_NAME=$(basename "$FILE_PATH" .dsl)
          echo "name=$WORKSPACE_NAME" >> $GITHUB_OUTPUT

      - name: Push to Structurizr
        run: |
          /usr/local/structurizr-cli/structurizr.sh push \
            -id ${{ secrets[format('STRUCTURIZR_WORKSPACE_ID_{0}', steps.workspace-name.outputs.name)] }} \
            -key ${{ secrets[format('STRUCTURIZR_API_KEY_{0}', steps.workspace-name.outputs.name)] }} \
            -secret ${{ secrets[format('STRUCTURIZR_API_SECRET_{0}', steps.workspace-name.outputs.name)] }} \
            -url ${{ secrets.STRUCTURIZR_URL }} \
            -workspace ${{ steps.changed-files.outputs.workspace || steps.input-workspace.outputs.workspace }}
