name: Deploy Structurizr Diagrams

on:
  push:
    paths:
      - "**.dsl"
    branches:
      - main
  workflow_dispatch:
    inputs:
      workspace:
        required: true
        description: "Path of workspace to deploy structurizr/.dsl"
        type: string

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3

      - name: Get changed DSL files
        id: changed-files
        if: github.event_name == 'push'
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.dsl

      - name: Set matrix
        id: set-matrix
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "matrix={\"file\":[\"${{ github.event.inputs.workspace }}\"]}" >> $GITHUB_OUTPUT
          else
            FILES=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | xargs)
            JSON_ARRAY=$(echo "$FILES" | jq -R 'split(" ") | map(select(length > 0))')
            echo "matrix={\"file\":$JSON_ARRAY}" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: get-changes
    if: github.event_name == 'workflow_dispatch' || needs.get-changes.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/sebastienfi/structurizr-cli-with-bonus:latest
    strategy:
      matrix: ${{fromJson(needs.get-changes.outputs.matrix)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Extract workspace name
        id: workspace-name
        run: |
          FILE_PATH="${{ matrix.file }}"
          WORKSPACE_NAME=$(basename "$FILE_PATH" .dsl)
          echo "name=$WORKSPACE_NAME" >> $GITHUB_OUTPUT

      - name: Check required secrets
        id: check-secrets
        run: |
          WORKSPACE="${{ steps.workspace-name.outputs.name }}"
          MISSING_SECRETS=""

          if [ -z "${{ secrets[format('STRUCTURIZR_WORKSPACE_ID_{0}', steps.workspace-name.outputs.name)] }}" ]; then
            MISSING_SECRETS="$MISSING_SECRETS STRUCTURIZR_WORKSPACE_ID_$WORKSPACE"
          fi
          if [ -z "${{ secrets[format('STRUCTURIZR_API_KEY_{0}', steps.workspace-name.outputs.name)] }}" ]; then
            MISSING_SECRETS="$MISSING_SECRETS STRUCTURIZR_API_KEY_$WORKSPACE"
          fi
          if [ -z "${{ secrets[format('STRUCTURIZR_API_SECRET_{0}', steps.workspace-name.outputs.name)] }}" ]; then
            MISSING_SECRETS="$MISSING_SECRETS STRUCTURIZR_API_SECRET_$WORKSPACE"
          fi

          if [ ! -z "$MISSING_SECRETS" ]; then
            echo "Error: Missing required secrets for workspace $WORKSPACE:"
            echo "$MISSING_SECRETS"
            echo "Please create these secrets following the pattern: STRUCTURIZR_<TYPE>_<WORKSPACE_NAME>"
            exit 1
          fi

      - name: Push to Structurizr
        run: |
          /usr/local/structurizr-cli/structurizr.sh push \
            -id ${{ secrets[format('STRUCTURIZR_WORKSPACE_ID_{0}', steps.workspace-name.outputs.name)] }} \
            -key ${{ secrets[format('STRUCTURIZR_API_KEY_{0}', steps.workspace-name.outputs.name)] }} \
            -secret ${{ secrets[format('STRUCTURIZR_API_SECRET_{0}', steps.workspace-name.outputs.name)] }} \
            -url ${{ secrets.STRUCTURIZR_URL }} \
            -workspace ${{ matrix.file }}
