name: Deploy Structurizr Diagrams
on:
  push:
    paths:
      - "**.dsl"
    branches:
      - main
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed DSL files
        id: changed-files
        run: |
          BEFORE_SHA=${{ github.event.before }}
          AFTER_SHA=${{ github.event.head }}

          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT ${BEFORE_SHA}..${AFTER_SHA} -- "*.dsl")

          if [ -n "$CHANGED_FILES" ]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
            echo "all_changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set matrix
        id: set-matrix
        run: |
          FILES_JSON=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | tr ' ' '\n' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "matrix={\"file\":$FILES_JSON}" >> $GITHUB_OUTPUT

  deploy:
    needs: check-changes
    if: needs.check-changes.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/sebastienfi/structurizr-cli-with-bonus:latest
    strategy:
      matrix: ${{fromJson(needs.check-changes.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Extract workspace name
        id: workspace-name
        run: |
          FILE_PATH="${{ matrix.file }}"
          WORKSPACE_NAME=$(basename "$FILE_PATH" .dsl)
          echo "name=$WORKSPACE_NAME" >> $GITHUB_OUTPUT

      - name: Push to Structurizr
        run: |
          /usr/local/structurizr-cli/structurizr.sh push \
          -id ${{ secrets[format('STRUCTURIZR_WORKSPACE_ID_{0}', steps.workspace-name.outputs.name)] }} \
          -key ${{ secrets[format('STRUCTURIZR_API_KEY_{0}', steps.workspace-name.outputs.name)] }} \
          -secret ${{ secrets[format('STRUCTURIZR_API_SECRET_{0}', steps.workspace-name.outputs.name)] }} \
          -url ${{ secrets.STRUCTURIZR_URL }} \
          -workspace ${{ matrix.file }}
