name: Deploy Structurizr Diagrams

on:
  push:
    paths:
      - "**.dsl"
    branches:
      - main
  workflow_dispatch:
    inputs:
      workspace:
        required: true
        description: "Path of workspace to deploy structurizr/.dsl"
        type: string

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
      - name: Get changed DSL files
        id: changed-files
        if: github.event_name == 'push'
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.dsl

  deploy:
    needs: get-changes
    runs-on: ubuntu-latest
    container: ghcr.io/sebastienfi/structurizr-cli-with-bonus:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set workspace from input
        id: input-workspace
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "workspace=${{ github.event.inputs.workspace }}" >> $GITHUB_OUTPUT

      - name: Set workspace from changed files
        id: changed-workspace
        if: github.event_name == 'push'
        shell: bash
        run: |
          if [ "${{ needs.get-changes.outputs.any_changed }}" = "true" ]; then
            echo "workspace=${{ needs.get-changes.outputs.changed_files }}" >> $GITHUB_OUTPUT
          else
            echo "No DSL files were changed"
            exit 0
          fi

      - name: Extract workspace name
        id: workspace-name
        if: github.event_name == 'workflow_dispatch' || needs.get-changes.outputs.any_changed == 'true'
        run: |
          FILE_PATH="${{ steps.changed-workspace.outputs.workspace || steps.input-workspace.outputs.workspace }}"
          WORKSPACE_NAME=$(basename "$FILE_PATH" .dsl)
          echo "name=$WORKSPACE_NAME" >> $GITHUB_OUTPUT

      - name: Push to Structurizr
        if: github.event_name == 'workflow_dispatch' || needs.get-changes.outputs.any_changed == 'true'
        run: |
          /usr/local/structurizr-cli/structurizr.sh push \
            -id ${{ secrets[format('STRUCTURIZR_WORKSPACE_ID_{0}', steps.workspace-name.outputs.name)] }} \
            -key ${{ secrets[format('STRUCTURIZR_API_KEY_{0}', steps.workspace-name.outputs.name)] }} \
            -secret ${{ secrets[format('STRUCTURIZR_API_SECRET_{0}', steps.workspace-name.outputs.name)] }} \
            -url ${{ secrets.STRUCTURIZR_URL }} \
            -workspace ${{ steps.changed-workspace.outputs.workspace || steps.input-workspace.outputs.workspace }}
